#!/usr/bin/env python3
"""Artifact-only batch bridge. Model judgments are never generated by this code."""
from __future__ import annotations
import argparse
import hashlib
import io
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import zipfile

from pipeline_state import BATCHES

ROOT = Path(__file__).resolve().parent
REQUEST_DIR = ROOT / '.job_watch_bridge' / 'requests'
VERSION = '2.0'
MAX_LIMIT = 20
ID_RE = re.compile(r'[A-Za-z0-9][A-Za-z0-9_-]{0,119}')


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


def safe_id(value):
    if not isinstance(value, str) or not ID_RE.fullmatch(value):
        raise ValueError('request_id_invalid')
    return value


def load_request(path):
    path = path.resolve()
    if REQUEST_DIR.resolve() not in path.parents or path.parent != REQUEST_DIR.resolve() or path.suffix != '.json':
        raise ValueError('request_path_outside_bridge')
    data = json.loads(path.read_text())
    if not isinstance(data, dict) or data.get('version') != VERSION:
        raise ValueError('request_version_invalid')
    from job_memory import assert_no_jd
    assert_no_jd(data)
    if safe_id(data.get('request_id')) != path.stem:
        raise ValueError('request_id_filename_mismatch')
    if data.get('action') not in {'select', 'apply'} or data.get('batch') not in BATCHES:
        raise ValueError('request_action_or_batch_invalid')
    fields = {'version','request_id','action','batch','retry_attempt'}
    fields |= ({'limit','fetch','exclude_keys','expected_job_key','expected_fingerprint'} if data['action'] == 'select'
               else {'parent_request_id','select_run_id','packet_sha256','patch'})
    if set(data) - fields:
        raise ValueError('request_fields_invalid')
    if data['action'] == 'select':
        validate_select_request(data)
    else:
        validate_apply_request(data)
    return data


def validate_select_request(data):
    limit = data.get('limit')
    if type(limit) is not int or not 1 <= limit <= MAX_LIMIT:
        raise ValueError('select_limit_invalid')
    if data.get('fetch') is not True:
        raise ValueError('select_requires_fetch')
    exclusions = data.get('exclude_keys', [])
    if not isinstance(exclusions, list) or len(exclusions) > 100 or any(not isinstance(k, str) or not k for k in exclusions):
        raise ValueError('exclude_keys_invalid')
    for field in ('expected_job_key', 'expected_fingerprint'):
        if field in data and not str(data.get(field) or '').strip():
            raise ValueError(field + '_invalid')


def validate_apply_request(data):
    safe_id(data.get('parent_request_id'))
    if type(data.get('select_run_id')) is not int or data['select_run_id'] <= 0:
        raise ValueError('select_run_id_missing')
    if not re.fullmatch('[a-f0-9]{64}', str(data.get('packet_sha256', ''))):
        raise ValueError('packet_sha256_invalid')
    patch = data.get('patch')
    if not isinstance(patch, dict) or set(patch) != {'batch', 'snapshot', 'semantic_decisions'}:
        raise ValueError('patch_fields_invalid')
    if patch['batch'] != data['batch']:
        raise ValueError('patch_batch_mismatch')
    if not isinstance(patch['snapshot'], dict) or not patch['snapshot']:
        raise ValueError('patch_snapshot_missing')
    decisions = patch['semantic_decisions']
    if not isinstance(decisions, dict) or not 1 <= len(decisions) <= MAX_LIMIT:
        raise ValueError('patch_decision_count_invalid')
    from job_memory import assert_no_jd, assert_no_evidence_refs
    # Never commit full JD text or unresolved storage references in a request.
    assert_no_jd(decisions)
    assert_no_evidence_refs(decisions)
    return patch


def _run_json_command(args):
    proc = subprocess.run(args, cwd=ROOT, text=True, capture_output=True)
    # Never echo stdout/stderr: failed JSON decoding can otherwise leak a JD to logs.
    if proc.returncode:
        raise RuntimeError('worker_command_failed:exit=' + str(proc.returncode))
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError:
        raise RuntimeError('worker_returned_non_json') from None


def select(data, output, persist=True):
    from pipeline_state import writer_lock
    with writer_lock(ROOT):
        old = existing_receipt(data, locked=True)
        if old:
            # A logical SELECT never changes meaning, even if its artifact expired.
            output.unlink(missing_ok=True)
            return {**old, 'replayed':True}
        return _select(data, output, persist)


def _select(data, output, persist):
    validate_select_request(data)
    args = [sys.executable, 'semantic_worker.py', 'select', data['batch'], '--limit', str(data['limit']), '--fetch']
    for key in data.get('exclude_keys', []):
        args += ['--exclude-key', key]
    packet = _run_json_command(args)
    records = packet.get('records', [])
    if records:
        if data.get('expected_job_key') and records[0]['job_key'] != data['expected_job_key']:
            raise ValueError('unexpected_first_job')
        if data.get('expected_fingerprint') and records[0]['fingerprint'] != data['expected_fingerprint']:
            raise ValueError('unexpected_fingerprint')
    elif data.get('expected_job_key'):
        raise ValueError('expected_job_missing')
    errors = {}
    for rec in records:
        if rec.get('jd_error') or not (rec.get('jd') or {}).get('text'):
            errors[rec['job_key']] = rec.get('jd_error') or 'jd_missing'
    packet.update(version=VERSION, request_id=data['request_id'], select_run_id=int(os.environ.get('GITHUB_RUN_ID', '0')),
                  select_run_attempt=int(os.environ.get('GITHUB_RUN_ATTEMPT', '1')))
    output.write_text(json.dumps(packet, ensure_ascii=False, sort_keys=True))
    from pipeline_state import now, transaction
    result = {'version':VERSION, 'request_id':data['request_id'], 'request_sha256':digest(data),
            'created_at':now(), 'action':'select', 'batch':data['batch'],
            'status':'EMPTY' if not records else 'PARTIAL' if errors else 'READY',
            'record_count':len(records), 'ready_count':len(records)-len(errors),
            'job_keys':[r['job_key'] for r in records], 'fetch_errors':errors,
            'fingerprints':{r['job_key']:r['fingerprint'] for r in records},
            'select_run_id':packet['select_run_id'], 'select_run_attempt':packet['select_run_attempt'],
            'snapshot':packet.get('snapshot'),
            'artifact_name':f"job-watch-packet-{packet['select_run_id']}-{packet['select_run_attempt']}",
            'packet_sha256':hashlib.sha256(output.read_bytes()).hexdigest()}
    name = receipt_name(data)
    (ROOT / Path(name).parent).mkdir(parents=True, exist_ok=True)
    if persist:
        transaction({name:result}, root=ROOT)
    return result


def receipt_name(data):
    return '.job_watch_bridge/receipts/' + safe_id(data['request_id']) + '.json'


def existing_receipt(data, locked=False):
    if not locked:
        from pipeline_state import writer_lock
        # Recover memory+receipt BEFORE replay and snapshot checks.
        with writer_lock(ROOT):
            return existing_receipt(data, locked=True)
    path = ROOT / receipt_name(data)
    if not path.exists():
        return None
    receipt = json.loads(path.read_text())
    if (receipt.get('request_sha256') != digest(data) or receipt.get('request_id') != data['request_id']
            or receipt.get('action') != data['action'] or receipt.get('batch') != data['batch']):
        raise ValueError('request_id_reused_with_different_content')
    return receipt


def finalize_select(data, result, packet_path, artifact_id):
    """Publish metadata only after upload succeeded, pinning that exact artifact."""
    from pipeline_state import writer_lock, transaction
    from semantic_worker import batch_snapshot
    with writer_lock(ROOT):
        old = existing_receipt(data, locked=True)
        if old:
            return {**old, 'replayed':True}
        if (data.get('action') != 'select' or result.get('version') != VERSION or result.get('batch') != data['batch']
                or type(artifact_id) is not int or artifact_id <= 0 or result.get('request_sha256') != digest(data)
                or result.get('request_id') != data['request_id'] or result.get('action') != 'select'
                or result.get('select_run_id') != int(os.environ['GITHUB_RUN_ID'])
                or result.get('select_run_attempt') != int(os.environ['GITHUB_RUN_ATTEMPT'])
                or result.get('snapshot') != batch_snapshot(data['batch'], ROOT)
                or result.get('artifact_name') != f"job-watch-packet-{result['select_run_id']}-{result['select_run_attempt']}"
                or hashlib.sha256(packet_path.read_bytes()).hexdigest() != result.get('packet_sha256')):
            raise ValueError('select_finalization_mismatch')
        result = {**result, 'artifact_id':artifact_id}
        name = receipt_name(data)
        (ROOT / Path(name).parent).mkdir(parents=True, exist_ok=True)
        transaction({name:result}, root=ROOT)
        return result


def canonical_select(data, packet=None):
    path = ROOT / '.job_watch_bridge/receipts' / (safe_id(data['parent_request_id']) + '.json')
    if not path.exists():
        raise ValueError('canonical_select_receipt_missing')
    parent = json.loads(path.read_text())
    if (parent.get('action') != 'select' or parent.get('request_id') != data['parent_request_id']
            or parent.get('batch') != data['batch'] or parent.get('select_run_id') != data['select_run_id']
            or parent.get('packet_sha256') != data['packet_sha256']):
        raise ValueError('canonical_select_binding_mismatch')
    if packet is not None:
        records = packet['records']
        if (parent.get('job_keys') != [r['job_key'] for r in records]
                or parent.get('fingerprints') != {r['job_key']:r['fingerprint'] for r in records}
                or ('snapshot' in parent and parent['snapshot'] != packet.get('snapshot'))
                or ('select_run_attempt' in parent and parent['select_run_attempt'] != packet.get('select_run_attempt'))):
            raise ValueError('canonical_select_membership_mismatch')
    return parent


def download_packet(data, output):
    """Download only the artifact of the verified select run; no JD in Git or logs."""
    if existing_receipt(data):
        return {'status':'REPLAY', 'request_id':data['request_id']}
    canonical = canonical_select(data)
    import requests
    repo = os.environ['GITHUB_REPOSITORY']
    headers = {'Authorization':'Bearer ' + os.environ['GH_TOKEN'], 'Accept':'application/vnd.github+json'}
    base = 'https://api.github.com/repos/' + repo
    def get(url):
        response = requests.get(url, headers=headers, timeout=45)
        if response.status_code != 200:
            raise RuntimeError('artifact_api_failed:status=' + str(response.status_code))
        return response
    run = get(base + '/actions/runs/' + str(data['select_run_id'])).json()
    if (run.get('head_branch') != os.environ['GITHUB_REF_NAME'] or run.get('event') != 'push'
            or run.get('conclusion') != 'success' or run.get('path') != '.github/workflows/chatgpt_job_watch_bridge.yml'):
        raise ValueError('select_run_not_verified')
    parent_path = '.job_watch_bridge/requests/' + safe_id(data['parent_request_id']) + '.json'
    parent_proc = subprocess.run(['git','show',run['head_sha'] + ':' + parent_path], cwd=ROOT, capture_output=True, text=True)
    if parent_proc.returncode:
        raise ValueError('select_parent_missing')
    parent = json.loads(parent_proc.stdout)
    if (parent.get('action') != 'select' or parent.get('batch') != data['batch']
            or parent.get('request_id') != data['parent_request_id'] or digest(parent) != canonical.get('request_sha256')):
        raise ValueError('select_parent_mismatch')
    items = get(base + '/actions/runs/' + str(data['select_run_id']) + '/artifacts').json()['artifacts']
    name = canonical.get('artifact_name') or 'job-watch-packet-' + run['head_sha']
    matches = [a for a in items if a['name'] == name and not a['expired']]
    if len(matches) != 1 or ('artifact_id' in canonical and matches[0]['id'] != canonical['artifact_id']):
        raise ValueError('select_artifact_missing_or_expired')
    raw = get(base + '/actions/artifacts/' + str(matches[0]['id']) + '/zip').content
    with zipfile.ZipFile(io.BytesIO(raw)) as archive:
        entry = archive.getinfo('job-watch-packet.json')
        if entry.file_size > 16_000_000:
            raise ValueError('packet_too_large')
        payload = archive.read(entry)
    if hashlib.sha256(payload).hexdigest() != data['packet_sha256']:
        raise ValueError('packet_hash_mismatch')
    output.write_bytes(payload)
    return {'status':'DOWNLOADED', 'request_id':data['request_id']}


def pending_counts():
    from sync_analysis_state import project_batch
    counts = {b.upper():len(project_batch(b, ROOT)['queue']) for b in BATCHES}
    return {'by_batch':counts, 'total':sum(counts.values())}


def apply(data, patch_path, receipt_path, packet_path):
    from pipeline_state import writer_lock
    with writer_lock(ROOT):
        return _apply(data, patch_path, receipt_path, packet_path)


def _apply(data, patch_path, receipt_path, packet_path):
    from semantic_worker import apply_packet, batch_snapshot
    from sync_analysis_state import project_batch
    from harden_job_watch_state import semantic_decision_valid
    from pipeline_state import transaction
    patch = validate_apply_request(data)
    old = existing_receipt(data, locked=True)
    if old:
        result = {**old, 'replayed':True, 'applied_count':0}
        receipt_path.write_text(json.dumps(result, indent=2))
        return result
    raw = packet_path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != data['packet_sha256']:
        raise ValueError('packet_hash_mismatch')
    packet = json.loads(raw)
    if (packet.get('version') != VERSION or packet.get('batch') != data['batch']
            or packet.get('request_id') != data['parent_request_id'] or packet.get('select_run_id') != data['select_run_id']
            or packet.get('snapshot') != patch['snapshot']):
        raise ValueError('packet_binding_mismatch')
    records = packet.get('records')
    if not isinstance(records, list) or len(records) > MAX_LIMIT:
        raise ValueError('packet_records_invalid')
    bykey = {r['job_key']:r for r in records}
    if len(bykey) != len(records) or not set(patch['semantic_decisions']) <= set(bykey):
        raise ValueError('decision_outside_selected_packet')
    canonical_select(data, packet)
    if patch['snapshot'] != batch_snapshot(data['batch'], ROOT):
        raise ValueError('stale_worker_snapshot')
    projection = project_batch(data['batch'], ROOT)['records']
    valid, retry = {}, {}
    for key, decision in patch['semantic_decisions'].items():
        selected, rec = bykey[key], projection.get(key, {})
        if selected.get('jd_error') or not (selected.get('jd') or {}).get('text'):
            retry[key] = 'jd_not_available'
        elif selected.get('fingerprint') != rec.get('fingerprint'):
            retry[key] = 'selected_fingerprint_mismatch'
        elif not rec.get('current_open') or rec.get('user_decision') in {'APPLIED','NOT_INTERESTED'}:
            retry[key] = 'vacancy_no_longer_eligible'
        else:
            ok, reason = semantic_decision_valid(decision, rec)
            if ok:
                valid[key] = decision
            else:
                retry[key] = reason
    # Fetch failures and omitted reviews stay visible even when not submitted in patch.
    for key in set(bykey) - set(patch['semantic_decisions']):
        retry[key] = 'jd_fetch_failed' if bykey[key].get('jd_error') else 'review_not_submitted'
    before = pending_counts()
    accepted = {**patch, 'semantic_decisions':valid}
    receipt = {'version':VERSION, 'request_id':data['request_id'], 'request_sha256':digest(data),
               'parent_request_id':data['parent_request_id'], 'packet_sha256':data['packet_sha256'],
               'select_run_id':data['select_run_id'], 'snapshot':patch['snapshot'],
               'action':'apply', 'batch':data['batch'], 'status':'PARTIAL' if retry else 'COMPLETE',
               'applied_count':len(valid), 'applied_keys':sorted(valid), 'retry':retry,
               'accepted_patch_sha256':digest(accepted), 'pending_before':before, 'replayed':False}
    name = receipt_name(data)
    (ROOT / Path(name).parent).mkdir(parents=True, exist_ok=True)
    patch_path.write_text(json.dumps(accepted, ensure_ascii=False, sort_keys=True))
    if valid:
        applied = apply_packet(data['batch'], accepted, ROOT, bridge_receipt=(name, receipt), locked=True)
        if applied != len(valid):
            raise ValueError('accepted_patch_replay_without_request_receipt')
    else:
        transaction({name:receipt}, root=ROOT)
    result = {**receipt, 'pending_after':pending_counts()}
    receipt_path.write_text(json.dumps(result, ensure_ascii=False, indent=2) + '\n')
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--request', required=True, type=Path)
    parser.add_argument('--packet-output', type=Path)
    parser.add_argument('--packet-input', type=Path, default=Path('/tmp/job-watch-packet.json'))
    parser.add_argument('--download-packet', action='store_true')
    parser.add_argument('--finalize-select', type=int, metavar='ARTIFACT_ID')
    parser.add_argument('--patch-output', type=Path, default=Path('/tmp/job-watch-bridge-patch.json'))
    parser.add_argument('--receipt-output', type=Path, default=Path('/tmp/job-watch-bridge-apply-receipt.json'))
    args = parser.parse_args()
    data = load_request(args.request)
    if args.finalize_select is not None:
        result = finalize_select(data, json.loads(args.receipt_output.read_text()), args.packet_input, args.finalize_select)
        args.receipt_output.write_text(json.dumps(result, ensure_ascii=False, sort_keys=True))
    elif args.download_packet:
        result = download_packet(data, args.packet_input)
    elif data['action'] == 'select':
        if not args.packet_output:
            parser.error('--packet-output required for select')
        result = select(data, args.packet_output, persist=False)
        with open(os.environ['GITHUB_OUTPUT'], 'a') if os.environ.get('GITHUB_OUTPUT') else open(os.devnull, 'w') as out:
            print('replayed=' + str(result.get('replayed', False)).lower(), file=out)
    else:
        result = apply(data, args.patch_output, args.receipt_output, args.packet_input)
    print(json.dumps(result, ensure_ascii=False, sort_keys=True))


if __name__ == '__main__':
    main()
